
CREATE DATABASE product;
GRANT ALL PRIVILEGES ON DATABASE product TO postgres;


CREATE DATABASE media;
GRANT ALL PRIVILEGES ON DATABASE media TO postgres;


CREATE DATABASE account;
GRANT ALL PRIVILEGES ON DATABASE account TO postgres;