server:
  port: 9090

gateway:
  auth: http://localhost:9091
  product: http://localhost:9094
  media: http://localhost:9095
  inventory: http://localhost:9096

spring:
  application:
    name: api-getaway
  profiles:
    active: "dev"
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO

---
spring:
  config:
    activate:
      on-profile: "dev"
#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowed-origins: "*"
#            allowed-methods: "*"
#            allowed-headers: "*"
#            allow-credentials: true
#      routes:
#        - id: auth
#          uri: http://localhost:9091
#          predicates:
#            - Path=/api/v1/auth/**
#          filters:
#            - RewritePath=(?<segment>.*), $\{segment}
#        - id: product
#          uri: http://localhost:9093
#          predicates:
#            - Path=/api/v1/product/**
#          filters:
#            - RewritePath=/api/v1/product/(?<segment>.*), $\{segment}
