server:
  port: 9090

spring:
  application:
    name: api-getaway
  profiles:
    active: "dev"

logging:
  pattern:
    level: ""

---
spring:
  config:
    activate:
      on-profile: "dev"
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=(?<segment>.*), $\{segment}
        - id: product
          uri: http://localhost:9092
          predicates:
            - Path=/api/v1/product/**
          filters:
            - RewritePath=/api/v1/product/(?<segment>.*), $\{segment}
