import '@testing-library/jest-dom';
import { metadata } from '@/app/layout';

describe('Test welcome tab title', () => {
  it('Test get title', () => {
    const msg = 'Create Next App';

    expect('Create Next App').toEqual(msg);
  });

  it('Check data', () => {
    expect(metadata.title).toEqual('Create Next App');
  });

  it('Check description', () => {
    expect(metadata.description).toEqual('Generated by create next app');
  });
});
