import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import dynamic from 'next/dynamic'

const StoreProvider = dynamic(() => import('./StoreProvider'), { ssr: false })

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'E-Store Management System',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <StoreProvider>
                    {children}
                    <ToastContainer />
                </StoreProvider>
            </body>
        </html>
    )
}
