name: product section service ci

on:
  push:
    branches: ["main"]
    paths:
      - "fe-product/**"
      - ".github/workflows/ci-fe-product.yml"
      - ".github/workflows/actions-fe/**"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "fe-product/**"
      - ".github/workflows/ci-fe-product.yml"
      - ".github/workflows/actions-fe/**"

  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Generate folder name
        id: get-folder
        run: echo "folder=fe-product" >> $GITHUB_OUTPUT
        shell: bash
      - uses: ./.github/workflows/actions-fe
      - run: npm run lint && npm run format:check
        working-directory: fe-product

  security:
    needs: "analyze"
    runs-on: "ubuntu-latest"
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Use only 'java' to analyze code written in Java, Kotlin or both
        # Use only 'javascript' to analyze code written in JavaScript, TypeScript or both
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:
      - uses: ./.github/workflows/actions-fe
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

  unit-test:
    needs: security
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: ./.github/workflows/actions-fe
      - run: npm run junit-test && npm run test:cover
        working-directory: fe-product
      - name: Analyze with sonar cloud
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: fe-product
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Unit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JEST Tests # Name of the check run which will be created
          path: fe-product/reports/jest-junit.xml # Path to test results
          reporter: jest-junit

  docker:
    needs: "unit-test"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: checkout version
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./.github/workflows/actions-fe
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_MASTER }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3
        with:
          context: ./fe-product
          push: true
          tags: ghcr.io/tanhaok/estore-fe-product:latest
