name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, Thanks for your first issue of eStore. We'll look at this issue soon!"
        pr-message: "Hello, Welcome to eStore. Let's build a micro architecture together!! 😊"
